[package]
name = "rust_algo_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

criterion = "0.3"
rand = "0.8"
rayon = "1.5"
itertools = "0.9"
csv = "1.1"
num_cpus = "1.14"